### PR TITLE
Fix macOS build with d3d10

### PR DESCRIPTION
**Pull request by flukejones**
Change from `d3d11_dep` to `lib_d3d11` in dependencies.

This change will conflict with upstream when a newer version is merged.

### CODE REVIEW

**Comment by jmannanc** [comment]
This was already fixed in https://github.com/doitsujin/dxvk/commit/ff604d5a53428af4bf49e4f87b619d989a62051f like you said. I would wait until a new version is released on upstream so as to avoid merge conflicts. 

👎

**Comment by flukejones** [comment]
That commit you linked doesn't actually fix the issue - it works only for winelib builds. I created a PR upstream at same time as this one that does fix it.

**Comment by jmannanc** [comment]
Oh that's my bad. If you created a PR upstream, then why make another one here?

**Comment by flukejones** [comment]
The intention was to get it building for macOS quickly. But yeah I guess just getting it done upstream would be best in the long run.

**Pull request closed without merging**
